- name: Check if we have kernal image repository
  stat:
    path: "{{ pi_libvirt_boot }}"
  register: pool_image_img

- name: Copy raspberrypi qcow2 image, kernal and device_tree_binary_blob to libvirt folder, set kernal and dtb to read only.
  become: true
  become_method: sudo
  when: not pool_image_img.stat.exists
  copy:
    src: "{{ item.src }}"
    dest: "{{ pi_libvirt_pool_dir }}"
    owner: libvirt-qemu
    group: kvm
    mode: "{{ item.mode | default(0644) }}"
  with_items:
    - src: "{{ pi_image_qcow2_path }}"
    - src: "{{ pi_kernal_path }}"
      mode: "0444"
    - src: "{{ pi_device_tree_blob_path }}"
      mode: "0444"
