---
- name: Check if we have raspberry pi image.
  stat:
    path: "{{ pi_image_img_path }}"
  register: rapi_image

- name: Get raspberry pi .img
  include: "get_os_image.yml"
  when: not rapi_image.stat.exists

- name: Create qcow2 image
  include: "convert_img_to_qcow2.yml"

- name: Download kernal images
  include: "download_kernal_images.yml"

- name: Copy qcow2 image
  include: "copy_to_libvirt_pool.yml"

# defining and launching an LXC guest
- name: define vm
  virt:
    command: define
    xml: "{{ lookup('template', 'pi.xml.j2') }}"
  register: libvirt_pi_guest

- name: Create snapshot
  shell: virsh snapshot-create-as --domain {{ pi_libvirt_guest_name }} --name initial_snapshot
  when: libvirt_pi_guest.changed

- name: Start Raspberry Pi Configuration
  virt:
    name: "{{ pi_libvirt_guest_name }}"
    command: info
  register: libvirt_guest_pi
