---
- name: Check if we have raspberry pi image.
  stat:
    path: "{{ pi_image_img_path }}"
  register: rapi_image

- name: Get raspberry pi .img
  include: "get_os_image.yml"
  when: not rapi_image.stat.exists

- name: Create qcow2 image
  include: "convert_img_to_qcow2.yml"

- name: Download kernal images
  include: "download_kernal_images.yml"

- name: Create qcow2 image
  include: "copy_to_libvirt_pool.yml"

# defining and launching an LXC guest
- name: define vm
  virt:
    command: define
    xml: "{{ lookup('template', 'pi.xml.j2') }}"
