---
- name: Set path to Image ZIP
  set_fact:
     pi_image_zip_path: "temp/{{ gon_pi_zip_file_name }}"

- name: Check if we have raspberry pi iamge zip.
  stat:
    path: "{{ pi_image_zip_path }}"
  register: rapi_zip

- name: Downloads RaspiOS Zipped Image
  get_url:
    url: "{{ pi_image_zip_path }}"
    dest: temp/
  when: not rapi_zip.stat.exists

- name: Set img, cow2 and kernal paths
  set_fact:
     pi_image_img_path: "{{ pi_image_zip_path | replace('.zip', '.img') }}"
     pi_image_qcow2_path: "{{ pi_image_zip_path | replace('.zip', '.qcow2') }}"
     pi_kernal_folder_path: "temp/qemu-rpi-kernal"

- name: Check if we have raspberry pi image.
  stat:
    path: "{{ pi_image_img_path }}"
  register: rapi_image

- name: Extract RaspiOS .zip to .img
  unarchive:
    src: "{{ pi_image_zip_path }}"
    dest: temp/
  when: not rapi_image.stat.exists

- name: Check if we have kernal image repository
  stat:
    path: "{{ pi_kernal_folder_path }}"
  register: rapi_kernals

- git:
    repo: 'https://github.com/dhruvvyas90/qemu-rpi-kernel.git'
    dest: temp/qemu-rpi-kernal
    version: "{{gon_kernal_repo_sha}}"
  when: not rapi_kernals.stat.exists
